### PR TITLE
Adds editing variable capability

### PR DESCRIPTION
**Pull request by jessicagomesng**
Add option for users to edit variables - prefill the modal with the previous content, and then add functionality to validate & edit the variable

### CODE REVIEW

**Comment by manonz** [comment]
I had look at the editing work you have done, it looks good. I could not change the min value of the randomExample from 1 to 4 (Have this validation error: Min must be less than max.).  The modal buttons: can we call them OK and Close (rather than Edit and Close), this will work for creating new variables as well.

**Review by manonz — COMMENTED** [review]
I had a look at the editing work you have done, it looks good. I could not change the min value of the randomExample from 1 to 4 (Have this validation error: Min must be less than max.).  The modal buttons: can we call them OK and Close (rather than Edit and Close), this will work for creating new variables as well.

**Comment by jessicagomesng** [comment]
Hi @manonz  - sorry this is so delayed, had a busy month at work! I've made the suggested fixes but not the one for the min/max - there's an additional validation check now to make sure that the min < max prior to processing the random number. I can take it out if you like though!

Thanks for your patience

**Comment by manonz** [comment]
> Hi @manonz - sorry this is so delayed, had a busy month at work! I've made the suggested fixes but not the one for the min/max - there's an additional validation check now to make sure that the min < max prior to processing the random number. I can take it out if you like though!
> 
> Thanks for your patience

Thanks @jessicagomesng Looks great. Can we merge this with the main branch to publish it?

**Comment by manonz** [comment]
Hmm, I merged it, but editing variables is flaky. It looks like once we get the "Min must be less than max." error, then adding new random variables don't work - sometimes nothing happens, and sometimes it overrides the "randomExample".

**Comment by manonz** [comment]
Okay @jessicagomesng, I have fixed the above two issues. The spurious "Min must be less than max." appeared to come from string comparison rather than numeric comparison. The second issue appeared to come from the onclick event handler being set to Edit processing so any new Add variables ceases to work. The fix for the second issue is a hack, so you might want to look at a cleaner way to fix this if you have some time.

**Pull request merged**
